#!/bin/bash
DDOC=$(cat <<-END
     folder size    ~/
     folder topfile ~/ 20

     

END
)

#### Global Config. #################################
# set -x  # Output commands being run.
set -e  # Exit on error.

#### Global vars ###################################
FUNAME=`basename "$0"`
NOW=$(date '+%Y%m%d')
#echo "######### ${me} #############################"
#echo "$NOW"


### Input Params. ##################################
[ $# -eq 0 ] &&    echo $DDOC && exit    #### No input print doc
ddo="size"  &&  [ -z $1 ] && export ddo=$1
ppath="~/"  &&  [ -z $2 ] && export ppath=$2
ssize=20    &&  [ -z $3 ] && export ssize=$3


### Core ###########################################
if [[ "$ddo" = size ]]; then
   df -h $ppath
   echo  # Newline
   du -h --max-depth=5. $ppath / |\
      /bin/grep '[0-9]G\>' |\
      /usr/bin/sort -hr 
      
   exit 0

elif [[ "$ddo" = topfile ]]; then
   df -H $ppath
   echo  # Newline
   du -a . --exclude='${HOME}/zdropbox' |\
      sort -n -r |\
      head -n $ssize  
      
   exit 0

   
else
   echo $DDOC
fi












