version: '3.7'

services:
  localstack:
    image: localstack/localstack:0.14.4
    ports:
      - 4566:4566 # すべてのサービスポート
      - 8000:8080 # dashboard
    volumes:
      # 初回起動スクリプト
      - ./docker/localstack:/docker-entrypoint-initaws.d
      # おまじない
      - /var/run/docker.sock:/var/run/docker.sock
      # データのマウント
      - 'localstack-data:/tmp/localstack'
    environment:
      # 有効にするサービス
      - SERVICES=s3,dynamodb,ses
      # s3のpresignedUrl
      # https://docs.localstack.cloud/integrations/aws-cli/#setting-up-local-region-and-credentials-to-run-localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - DISABLE_CORS_CHECKS=1

volumes:
  localstack-data:
    driver: 'local'