version: '3.7'

services:
  ####### localstack #########################################
  localstack:
    image: localstack/localstack:0.14.4
    ports:
      - 4566:4566 #
      - 8000:8080 # dashboard
    volumes:
      - ./docker/localstack:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # 有効にするサービス
      - SERVICES=s3,iam,redshift
      # s3のpresignedUrl
      # https://docs.localstack.cloud/integrations/aws-cli/#setting-up-local-region-and-credentials-to-run-localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - DISABLE_CORS_CHECKS=1

  ####### MySQL  #############################################
  rds_mysql:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - 3306:3306
    # Connect via commandline: mysql -h 127.0.0.1 -P 3306 -u root -p
    environment:
      - MYSQL_ROOT_PASSWORD=test

  ###### Redis Cluster #######################################
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    ports:
      - "7001:6379"
      - "16378:16379"
    environment:
      - REDIS_PASSWORD=bitnami
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-5
      - REDIS_CLUSTER_ANNOUNCE_PORT=7001
      - REDIS_CLUSTER_ANNOUNCE_IP=192.168.50.4
      - REDIS_CLUSTER_BUS_ANNOUNCE_PORT=16368
      - REDIS_CLUSTER_DYNAMIC_IPS=no
    networks:
      cluster-redis:
        ipv4_address: 172.27.0.108

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    ports:
      - "7002:6379"
      - "16379:16379"
    environment:
      - REDIS_PASSWORD=bitnami
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-5
      - REDIS_CLUSTER_ANNOUNCE_PORT=7002
      - REDIS_CLUSTER_ANNOUNCE_IP=192.168.50.4
      - REDIS_CLUSTER_BUS_ANNOUNCE_PORT=16369
      - REDIS_CLUSTER_DYNAMIC_IPS=no
    networks:
      cluster-redis:
        ipv4_address: 172.27.0.105

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    # network_mode: "host"
    ports:
      - "6470:6379"
      - "16377:16379"
    depends_on:
      - redis-node-0
      - redis-node-1
    environment:
      - REDIS_PASSWORD=bitnami
      - REDISCLI_AUTH=bitnami
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-5
      - REDIS_CLUSTER_CREATOR=yes
      - REDIS_CLUSTER_ANNOUNCE_PORT=7003
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=192.168.50.4
    entrypoint: []
    command:
      - /bin/bash
      - -c
      - redis-cli -a bitnami --cluster create 192.168.50.4:6370 192.168.50.4:7002 192.168.50.4:7003 --cluster-replicas 1 --cluster-yes
      ### 192.168  IS your local Laptop host IP  ---> Make accessible through localhost
    networks:
      cluster-redis:
        ipv4_address: 172.27.0.106

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-5:
    driver: local

###### Issue in MacOS ---> need to create Bridge with local IP adress !!!!
networks:
  cluster-redis:
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: 172.27.0.0/16
